name: auto-format
on:
    push:

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Prettify code
              uses: creyD/prettier_action@v4.3
              with:
                  prettier_options: --tab-width 4 --ignore-unknown --print-width 110 --write **/**/*.{js,css}
                  prettier_version: "2.8.8"
                  only_changed: True
                  commit_message: "auto-format"
